server:
  port: 8080

spring:
  application:
    name: login-test
  main:
    allow-bean-definition-overriding: true
  # 热部署配置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
    livereload:
      enabled: true
      port: 35729
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10s
      ssl:
        enabled: false
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

redisson:
  single-server-config:
    address: redis://localhost:6379
    database: 0
    timeout: 3000
    connection-pool-size: 64
    connection-minimum-idle-size: 10

captcha:
  # 是否启用验证码校验
  enable: false
  # 验证码类型 math 数组计算 char 字符验证
  type: MATH
  # line 线段干扰 circle 圆圈干扰 shear 扭曲干扰
  category: CIRCLE
  # 数字验证码位数
  numberLength: 1
  # 字符验证码长度
  charLength: 4



# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: org.example.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  # 禁用banner
  banner: false
  # 禁用DDL功能
  check-config-location: false
  global-config:
    # 禁用DDL应用程序运行器
    enable-sql-runner: false
    db-config:
      # 主键类型
      id-type: ASSIGN_ID
      # 逻辑删除字段
      logic-delete-field: delFlag
      # 逻辑删除全局值（1表示已删除）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除）
      logic-not-delete-value: 0

# 多租户配置
tenant:
  # 是否启用多租户功能
  enable: true
  # 需要排除的表（这些表不会自动添加租户条件）
  excludeTables:
    - sys_tenant
    - sys_tenant_package
    - sys_config
    - sys_dict_type
    - sys_dict_data
    - sys_notice
    - sys_oss_config
    - sys_logininfor
    - sys_oper_log

# RSA加密配置
rsa:
  # 是否启用RSA加密
  enabled: true
  # RSA公钥（如果不配置，系统会自动生成）
  publicKey:
  # RSA私钥（如果不配置，系统会自动生成）
  privateKey:

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: 1800
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token前缀
  token-prefix: "Bearer"
  # 是否输出操作日志
  is-log: false
  # 是否从cookie中读取token
  is-read-cookie: false
  # 是否从header中读取token
  is-read-header: true
  # 是否从请求体中读取token
  is-read-body: true
  # jwt秘钥
  jwt-secret-key: abcdefghijklmnopqrstuvwxyz

# 日志配置
logging:
  level:
    root: INFO
    org.example: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Security配置
security:
  # 排除路径（这些路径不需要登录验证）
  excludes:
    # 静态资源
    - "/favicon.ico"
    - "/error"
    - "/assets/**"
    - "/webjars/**"
    - "/v3/api-docs/**"
    - "/swagger-ui/**"
    - "/swagger-resources/**"
    # 认证相关接口
    - "/auth/login"
    - "/auth/register"
    - "/auth/captcha"
    - "/auth/logout"
    # 登录接口（当前项目使用的路径）
    - "/login"
    - "/register"
    - "/captcha"
    # 系统配置接口（部分公开）
    - "/system/config/registerEnabled"
    - "/system/config/getConfigByKey"
    # 字典翻译接口（公开访问）
    - "/system/dict/type/list"
    - "/system/dict/type/getDictLabel"
    - "/system/dict/type/getDictValue"
    - "/system/dict/type/getDictData/**"
    - "/system/dict/type/getAllDict/**"
    # 加密相关接口
    - "/encrypt/rsa/publicKey"
    # 健康检查
    - "/actuator/health"
    - "/druid/**"
